"""
strategy.py
===========
Core generation engine for Stochastic Strategies.

Chord progressions are generated by sampling from a first-order Markov chain
over the 7 diatonic scale degrees (I–VII). The chain's transition matrix is
either loaded from a corpus-fitted .npy file (produced by fit_transition_matrix.py)
or falls back to a music-theory-informed prior.

Difficulty is controlled via temperature scaling τ on the base matrix P_base:

    P(τ)_ij = softmax(log(P_base_ij) / τ)_j

  τ → 0   : deterministic (always takes highest-probability transition)
  τ = 1   : recovers P_base
  τ → ∞   : uniform over all 7 degrees (maximum entropy)

Presets:
  Relaxed   τ = 0.5   H ≈ 1.0 bits/chord
  Challenge τ = 2.5   H ≈ 2.7 bits/chord  (near-maximum of log2(7) ≈ 2.81)

The Shannon entropy rate H of the chain at the chosen τ is reported on each
generated card as a quantitative difficulty signal.

Corpus reference:
    Kantarelis et al., "CHORDONOMICON: A Dataset of 666,000 Songs and their
    Chord Progressions", arXiv:2410.22046, 2024.
"""

import random
from pathlib import Path

import numpy as np

from stochastic_strategies.music_theory import (
    OBLIQUE_LIKE_STRATEGIES,
    DIATONIC_PROGRESSIONS,
    EXTENSIONS,
    TIME_SIGNATURES,
)

_DATA_DIR = Path(__file__).resolve().parent.parent / "data"

# ---------------------------------------------------------------------------
# Temperature presets
# ---------------------------------------------------------------------------
TAU_RELAXED   = 0.5
TAU_CHALLENGE = 2.5

# ---------------------------------------------------------------------------
# Scale-degree constants
# ---------------------------------------------------------------------------
DEGREE_NAMES_MAJOR = ["I", "II", "III", "IV", "V", "VI", "VII"]
MAJOR_INTERVALS    = [0, 2, 4, 5, 7, 9, 11]

# Chromatic insertion probability scales linearly with tau.
# At tau=2.5: p_chromatic = 0.25. At tau=0.5: p_chromatic = 0.05.
CHROMATIC_PROB_PER_TAU = 0.10


def minimal_repeating_unit[T](seq: list[T]) -> list[T]:
    """
    Return the shortest prefix of `seq` that tiles the whole sequence.

    Handles exact repetitions (A-B-C-A-B-C → A-B-C) and partial trailing
    repetitions (A-B-C-A-B → A-B-C), ensuring generated progressions never
    contain a repeated motif and reported lengths count the loop once.
    """
    n = len(seq)
    for p in range(1, n):
        if all(seq[i] == seq[i % p] for i in range(n)):
            return list(seq[:p])
    return list(seq)

# Music-theory-informed prior log-weight matrix.
# Rows = from-degree, columns = to-degree (I=0, II=1, ..., VII=6).
# Encodes standard voice-leading tendencies in pop/rock.
_W_PRIOR = np.array([
    # to:  I     II    III   IV    V     VI    VII
    [0.20, 0.30, 0.10, 1.80, 2.00, 0.50, 0.10],  # from I
    [0.50, 0.10, 0.10, 0.50, 2.50, 0.50, 0.10],  # from II
    [0.50, 0.10, 0.10, 0.50, 0.50, 2.50, 0.10],  # from III
    [2.20, 0.50, 0.10, 0.10, 2.20, 0.50, 0.10],  # from IV
    [3.50, 0.50, 0.10, 0.50, 0.10, 0.50, 0.10],  # from V
    [0.50, 2.00, 0.10, 2.00, 0.50, 0.10, 0.10],  # from VI
    [2.50, 0.50, 0.10, 0.50, 0.50, 0.50, 0.10],  # from VII
], dtype=np.float64)


# ---------------------------------------------------------------------------
# Matrix utilities
# ---------------------------------------------------------------------------

def _softmax_rows(W: np.ndarray) -> np.ndarray:
    """Numerically stable row-wise softmax."""
    W_s = W - W.max(axis=1, keepdims=True)
    exp_W = np.exp(W_s)
    return exp_W / exp_W.sum(axis=1, keepdims=True)


def _load_base_matrix(matrix_path: Path = _DATA_DIR / "transition_matrix.npy") -> np.ndarray:
    """
    Load a corpus-fitted (7,7) row-stochastic matrix from disk and return its
    log. Falls back to the theory-informed prior if the file is not found.
    """
    if matrix_path.exists():
        P = np.load(matrix_path)
        assert P.shape == (7, 7), f"Expected (7,7) matrix, got {P.shape}"
        return np.log(np.clip(P, 1e-12, None))
    return _W_PRIOR.copy()


_MAX_GENERATION_LENGTH = 7  # chorus loops longer than this are not generated


def _load_length_dist(matrix_path: Path = _DATA_DIR / "transition_matrix.npy") -> np.ndarray | None:
    """
    Load the empirical chorus-loop-length distribution produced by
    fit_transition_matrix.py, if present. Returns a 1-D probability array
    where index i corresponds to length i+1 (1-indexed), truncated and
    renormalized to _MAX_GENERATION_LENGTH. Returns None if the file does
    not exist, triggering the uniform fallback.
    """
    len_path = matrix_path.with_name(matrix_path.stem + "_lengths.npy")
    if len_path.exists():
        dist = np.load(len_path)[:_MAX_GENERATION_LENGTH]
        return dist / dist.sum()
    return None


def temperature_scale(log_W: np.ndarray, tau: float) -> np.ndarray:
    """
    Apply temperature τ to a log-weight matrix:

        P(τ)_ij = softmax(log_W_ij / τ)_j

    Parameters
    ----------
    log_W : (7, 7) log-weight matrix (unnormalized)
    tau   : temperature > 0

    Returns
    -------
    P : (7, 7) row-stochastic matrix
    """
    return _softmax_rows(log_W / tau)


# ---------------------------------------------------------------------------
# Entropy rate
# ---------------------------------------------------------------------------

def stationary_distribution(P: np.ndarray, tol: float = 1e-10,
                             max_iter: int = 10000) -> np.ndarray:
    """
    Stationary distribution via power iteration: π^(t+1) = π^(t) P,
    until max absolute change < tol.
    """
    pi = np.ones(7) / 7.0
    for _ in range(max_iter):
        pi_new = pi @ P
        if np.max(np.abs(pi_new - pi)) < tol:
            return pi_new
        pi = pi_new
    return pi


def entropy_rate(P: np.ndarray, pi: np.ndarray) -> float:
    """
    Shannon entropy rate of the Markov chain (bits per chord):

        H = -Σ_i π_i Σ_j P_ij log2(P_ij)

    Maximum possible: log2(7) ≈ 2.807 bits (uniform transition matrix).
    """
    log_P = np.where(P > 1e-15, np.log2(P), 0.0)
    return float(pi @ (-np.sum(P * log_P, axis=1)))


# ---------------------------------------------------------------------------
# Chord spelling helpers
# ---------------------------------------------------------------------------

NOTES_SHARP = ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"]


def chromatic_chord(key_root: str) -> str:
    """Return a random non-diatonic chord root in the given major key."""
    key_idx = NOTES_SHARP.index(key_root) if key_root in NOTES_SHARP else 0
    diatonic = {(key_idx + d) % 12 for d in MAJOR_INTERVALS}
    chromatic_roots = [NOTES_SHARP[i] for i in range(12) if i not in diatonic]
    return random.choice(chromatic_roots)


# ---------------------------------------------------------------------------
# Main class
# ---------------------------------------------------------------------------

class StochasticProgression:
    """
    Generates stochastic chord progressions, oblique strategies, time
    signatures, and tempos for the Stochastic Strategies songwriting tool.
    """

    def __init__(self, matrix_path: Path = _DATA_DIR / "transition_matrix.npy"):
        self._key: str | None = None
        self._progression: str | None = None
        self._strategy: str | None = None
        self._timesig: str | None = None
        self._tempo: int | None = None
        self._entropy: float | None = None

        self._log_W = _load_base_matrix(matrix_path)
        self._length_dist = _load_length_dist(matrix_path)
        self._using_corpus = matrix_path.exists()

    # ------------------------------------------------------------------
    # Internal generation
    # ------------------------------------------------------------------

    def _generate_progression(self, tau: float) -> None:
        """
        Generate a chord progression via temperature-scaled Markov sampling.

        Steps:
          1. Compute P(τ) and its entropy rate H(τ).
          2. Select a random key.
          3. Start from a degree sampled from the stationary distribution π.
          4. Walk the chain for 3–7 steps, inserting chromatic chords with
             probability p_chromatic = min(τ * 0.10, 0.40).
          5. Add diatonic extensions with probability proportional to τ.
        """
        P = temperature_scale(self._log_W, tau)
        pi = stationary_distribution(P)
        self._entropy = entropy_rate(P, pi)

        self._key = random.choice(list(DIATONIC_PROGRESSIONS.keys()))
        key_progression = DIATONIC_PROGRESSIONS[self._key]

        p_chromatic = min(tau * CHROMATIC_PROB_PER_TAU, 0.40)
        p_extension = min(tau * 0.15, 0.60)

        # Start from a degree drawn from the stationary distribution
        current_degree = int(np.random.choice(7, p=pi))
        if self._length_dist is not None:
            n_chords = int(np.random.choice(len(self._length_dist), p=self._length_dist)) + 1
        else:
            n_chords = random.randint(3, _MAX_GENERATION_LENGTH)
        chords = []

        for step in range(n_chords):
            if step > 0 and random.random() < p_chromatic:
                # Chromatic insertion: does not advance Markov state
                root = chromatic_chord(self._key)
                chord = root + (random.choice(EXTENSIONS) if random.random() < 0.5 else "")
                chords.append(chord)
            else:
                chord = key_progression[current_degree]
                if random.random() < p_extension:
                    chord += random.choice(EXTENSIONS)
                chords.append(chord)
                # Transition to next degree
                current_degree = int(np.random.choice(7, p=P[current_degree]))

        chords = minimal_repeating_unit(chords)
        self._progression = " - ".join(chords)

    def progression_randomizer_easy(self) -> None:
        """Relaxed mode: τ = 0.5, low entropy, high tonal predictability."""
        self._generate_progression(TAU_RELAXED)

    def progression_randomizer_hard(self) -> None:
        """Challenge mode: τ = 2.5, near-maximum entropy, high chromaticism."""
        self._generate_progression(TAU_CHALLENGE)

    # ------------------------------------------------------------------
    # Other randomizers
    # ------------------------------------------------------------------

    def strategy_randomizer(self) -> None:
        self._strategy = random.choice(OBLIQUE_LIKE_STRATEGIES)

    def time_randomizer(self) -> None:
        self._timesig = random.choice(TIME_SIGNATURES)

    def tempo_randomizer(self) -> None:
        self._tempo = random.randint(50, 200)

    # ------------------------------------------------------------------
    # Card rendering
    # ------------------------------------------------------------------

    def build_card(self) -> str:
        """
        Render the creative card. Includes progression, oblique strategy,
        time signature, tempo, and the chain entropy rate H (bits/chord).
        """
        width = 56

        def center(text: str) -> str:
            return f"│  {text.center(width)}  │"

        H_val = self._entropy or 0.0
        H_pct = H_val / np.log2(7) * 100
        entropy_str = f"H = {H_val:.2f} bits/chord  ({H_pct:.0f}% of max)"

        lines = [
            f"┌{'─' * (width + 4)}┐",
            f"│{' ' * (width + 4)}│",
            center("✦  S T O C H A S T I C   S T R A T E G I E S  ✦"),
            f"│{' ' * (width + 4)}│",
            f"├{'─' * (width + 4)}┤",
            f"│{' ' * (width + 4)}│",
            center(self._strategy or ""),
            f"│{' ' * (width + 4)}│",
            f"├{'─' * (width + 4)}┤",
            f"│{' ' * (width + 4)}│",
            center(self._progression or ""),
            f"│{' ' * (width + 4)}│",
            f"├{'─' * (width + 4)}┤",
            f"│{' ' * (width + 4)}│",
            center(f"{self._timesig}    ♩= {self._tempo}"),
            f"│{' ' * (width + 4)}│",
            f"├{'─' * (width + 4)}┤",
            f"│{' ' * (width + 4)}│",
            center(entropy_str),
            f"│{' ' * (width + 4)}│",
            f"└{'─' * (width + 4)}┘",
        ]

        return "\n".join(lines)
